### ISSUE TITLE
Dijagrami aktivnosti

### ISSUE THREAD

**Issue by ibecir** [ndzajic1/ooad-23-tim-zamger#19]
1. Grupni unos prisustva
   - Validacija unesenog linka, ne ide sa baklave a da ide od dijagrama, to je porgresno. Oboje idu od baklave.
2. Informisanje o mogućnosti upisa iduće godine + kolizija.png 
   - Svi slucajevi zavrsavaju u jednoj tacki a to nije dobro. Npr. Ako ne uspunjava uslove za koliziju onda je to neki interrupt u cijelom slucaju i treba da zavrsava sa crvenom prekriznom tackom kao u primjerima sa lab-a.
3. Pregled izvještaja o predmetu
   - Cijeli flow totalno pogresan. Prijava u sistem, pa odabir kursa. Mislim da treba da pocne od liste kurseva, pa odabir kursa, pa odabir izvjestaja. Samo mjenjanje ocjena treba biti u drugom dijagramu a ovaj dijagram treba da prikaze sam izvjestaj (ili vise izvjestaja koje nasstavnik moze odabrati)
5. Pregled ličnih podataka
   - Opet totalno pogresno i cilj vaseg dijagrama je da pokaze da se podatci mjenjaju u bazi. Ovdje treba da flow ide: odabir opcije pregleda licnih podataka, mogucnost izmjene i prikaz tih podataka korisniku.
6. Zaključivanje ocjene
   - Zakljucivanje ocjena je bulk opcija u sistemu na kraju semestra. Uslov je da je zbir svih ispita 100% i ukoliko je ispunjen uslov svim se studentima na jednu akciju zakljuce ocjene. Ocjene se ne zakljucuju po studentu nego je to bulk opcija. Jedini problem moze biti da nastavnik pokusava da zakljuci ocjenu kad nisu svi ispiti prosli (zbir svih ispita je ispod 100%)

Generalno:
Vecina dijagrama se fokusira na "bazu" i "prikaz" a u slucaju studentskog informacionog sistema dosta je stvari koje se mogu obraditi. Obradite zahtjeva kao sto su prijava na ispit, pravljenje grupa za labove, notifikacije studentima, kreiranje ispita i obavjestanje studenata o sivm tim aktivnostima a ovim dijagramima uvedite malo "reda". Kad kazem reda, nek to bude logicki sljed stvari, nista posebno ali je fokus na tome da se prikaze sam zahtjev. Znamo da mora da bude logovan na sistem kako bi ista uradio.

**Comment by dzaj1c** [comment]
@ibecir 
Dijagrami su popravljeni, uz napomenu da planiramo zahtjev 2  (upis i kolizija) zamijenimo funkcionalnijim zahtjevima za kreiranjem i prijavom ispita (dijagrami za nove aktivnosti su postavljeni), na tragu vaših savjeta na kraju posta, a pošto je prethodni zahtjev zaista suhoparan. Većina dijagrama aktivnosti završava sa informisanjem, i taj dio ćemo riješiti notifikacijama (planirana je i klasa Notifikacija), i tu ćemo imati nekih pitanja. Ako vam na prvu ne bude jasna ideja u nekom zahtjevu, možda da pogledate kako to otprilike treba da izgleda u korisničkom interfejsu. LP
