### ISSUE TITLE
Klasni i MVC Dijagram

### ISSUE THREAD

**Issue by ibecir** [ndzajic1/ooad-23-tim-zamger#26]
1. U klasnom dijagramu nema metoda, morate imati sve metode
2. Treba malo ljepse organizovati klase, sad trenutno izgledaju malo razbacano, hajmo to organizovati an na slici ispod

<img width="742" alt="image" src="https://github.com/ndzajic1/ooad-23-tim-zamger/assets/15219309/14bdb30f-47e4-46a9-8981-aaa112ccfc30">

3. Mislim da imate premalo kontrolera i da vam ova tri kontrolera postaju ogromni. Mozda ne bi bilo lose to razloziti na vise kontrolera (nema greske nikakve samo da ne budu ogromne klase sto na kraju dana nije ni problem ali postane tesko upravljati tim kodom)

**Comment by dzaj1c** [comment]
@ibecir
![mvcedit (1)](https://github.com/ndzajic1/ooad-23-tim-zamger/assets/115584541/cdc2a71c-c1e3-4b36-a636-782d2c2de71b)

**Comment by ibecir** [comment]
Super, ovo sad samo treba uraditi update i na klasnom dijagramj
