### ISSUE TITLE
Studentovi kursevi u Student Index View

### ISSUE THREAD

**Issue by asuta2** [ndzajic1/ooad-23-tim-zamger#38]
Nadograditi da u Sidebar studenta se pojave svi kursevi na koje je student prijavljen

**Comment by asuta2** [comment]
Isto i za profesora vjerovatno

**Comment by dzaj1c** [comment]
@asuta2  Prebacit ćemo ove viewove u HomeController, jer će StudentService kroz Index administratorski pristupati Student i Teacher objektima. Možeš raditi na njima dalje, poslije ćemo ih tamo prebaciti i poslati im šta treba kroz njihov metod u kontroleru.

**Comment by dzaj1c** [comment]
Home Controller je gotov, home viewovi su prebačeni u home controller, a Student i Teacher Indexi su vraćeni na staro. @asuta2 dalje ovdje razrađuješ te viewove, poslano ti je u ove home viewove sve što je potrebno iz baze. Biće da je lakše prvo ove viewove riješiti zbog orijentacije u aplikaciji.
