### ISSUE TITLE
StudentCourseStatus ne pronalazi dati kurs korektno

### ISSUE THREAD

**Issue by asuta2** [ndzajic1/ooad-23-tim-zamger#50]
Vidjeti branch studentchanges

**Comment by asuta2** [comment]
Valjda ne prosljeđujem korektan id ili nešto fali

**Comment by asuta2** [comment]
Iapk je problem to što Teacher objekat unutar StudentCourse.Course je null iako TeacherID nije

**Comment by asuta2** [comment]
@ndzajic1 možeš li provjeriti zašto svaki put kada dobaljvamo nešto StudentCourse tipa, nikad se ne vraća Teacher objekat iunutar Course objekta ako po modelu treba

**Comment by dzaj1c** [comment]
Jesi li Include(sc => sc.Course)? Ako i dalje neće, ručno postaviti Teachera prolaskom kroz listu StudentCourse u kontroleru.

**Comment by asuta2** [comment]
Okej, ručno sam stavio da ih pronalazi
